In [1]:
import time
import pandas as pd
from geopy import Nominatim
geolocator = Nominatim()
import json
from urllib.request import urlopen

## Import Dataset

In [25]:
dir = "/home/collier/Dropbox/Skills/Python/Projects/Real_Estate/htx_real_estate_analysis/"
file = pd.read_csv(dir+"all_details_20170922.csv",encoding = "ISO-8859-1")

In [26]:
file = file[pd.notnull(file['Zip Code'])]

In [27]:
file['zip_str'] = file['Zip Code'].astype(int)
file['zip_str'] = file['zip_str'].astype(str)

In [28]:
file['address_full'] = file['Address']+" "+file['City']+" "+file['zip_str']
file['lat'] = ""
file['lon'] = ""

In [29]:
file = file[["address_full","lat","lon"]]

In [30]:
dir = "/home/collier/Dropbox/Skills/Python/Projects/Real_Estate/walk_score_query_py/"
file_already_scraped = pd.read_csv(dir+"home_addresses_latlon_walkscores_08252017.csv",encoding = "ISO-8859-1")

In [31]:
file = file[~file['address_full'].isin(file_already_scraped['address_full'])]

In [32]:
file.shape

(407, 3)

## Collection of Address Locations (Lat&Lon)

In [33]:
for idx,row in file.iterrows():
    try:
        location = geolocator.geocode(row['address_full'])
        file.set_value(idx,'lat',location.latitude)
        file.set_value(idx,'lon',location.longitude)
    except:
        continue
    if idx % 200 == 0:
        print(idx)
    time.sleep(1)

2000

In [11]:
# file['lat'].value_counts(dropna=False)

In [57]:
# file.to_csv(dir+"home_addresses_latlon_082582017.csv")

## Collection of Walk,Transit,Bike Scores

In [2]:
dir = "C:/Users/David/Dropbox/Skills/Python/Projects/Real_Estate/walk_score_query_py/"
file = pd.read_csv(dir+"file_to_scrape.csv")

In [3]:
file['lat'] = file['lat'].astype(str)
file['lon'] = file['lon'].astype(str)
file['bike_score'] = ""
file['transit_score'] = ""
file['walk_score'] = ""
file = file[file['lat']!=""]

In [5]:
for idx, row in file.iterrows():
    addr = row['address_full']
    addr = addr.replace(" ","%20")
    lat = row['lat']
    lon = row['lon']
    addr_base = "http://api.walkscore.com/score?format=json&address="
    addr_base = addr_base + addr + "&lat=" + lat + "&lon=" + lon + "&transit=1" + "&bike=1" + "&wsapikey=33a9c4ba9c6f64219f47475fa9e7fd65"
    try:
        jsonurl = urlopen(addr_base)
        text = json.loads(jsonurl.read())
        scores_df = pd.DataFrame.from_dict(text)
        bike_score = scores_df.loc["score","bike"]
        transit_score = scores_df.loc["score","transit"]
        walk_score = scores_df.loc["score","walkscore"]
        file.set_value(idx,"bike_score",bike_score)
        file.set_value(idx,"transit_score",transit_score)
        file.set_value(idx,"walk_score",walk_score)
        del scores_df
    except:
        continue
    if idx % 200 == 0:
        print(idx)
    time.sleep(1)

0

ValueError: If using all scalar values, you must pass an index

In [7]:
file

,Unnamed: 0,address_full,lat,lon,bike_score,transit_score,walk_score
0,6,10018 Cedardale Dr Houston 77055,29.78997,-95.541302,53,40,60
1,8,10034 Larston Houston 77055,29.789641,-95.535433,52,38,57
2,14,1006 Adele St Houston 77009,29.806053,-95.386179,62,46,69
3,15,1006 B Enid Houston 77009,29.807884,-95.375452,61,56,58
4,16,1009 Gardendale Dr Houston 77018,29.8163436,-95.4203402,72,43,59
5,17,1009 St. Charles St Houston 77003,29.755026,-95.346869,77,81,73
6,34,1016 Studer St Houston 77007,29.7725768,-95.415454,65,42,82
7,69,1031 Ashland St Houston 77008,29.796141,-95.403483,71,43,72
8,80,1036 Walling St Houston 77009,29.8002005,-95.3810279,59,50,80
9,92,105 E 2nd St Houston 77007,29.7742004,-95.393147,58,45,55
10,94,1055 W 22nd St Houston 77008,29.805726,-95.418088,58,42,62
11,103,1101 Genova St Houston 77009,29.785185,-95.353893,55,63,61
12,109,1104 E 29th St Houston 77009,29.813271,-95.383753,61,47,59
13,113,1106 Reinerman St Houston 77007,29.779897,-95.413623,58,37,72
14,125,1111 Bunton Houston 77009,29.794039,-95.354152,51,52,61
15,129,1114 Detering St Houston 77007,29.780593,-95.415933,54,39,54
16,138,1117 E 23rd St Houston 77009,29.807546,-95.3844621,61,47,70
17,146,1120 E 16th St Houston 77009,29.799838,-95.386188,61,46,77
18,148,1120 W 21st St Houston 77008,29.804798,-95.425766,76,36,76
19,153,1123 Malone St Houston 77007,29.7689063,-95.419331,63,43,79
20,154,1123 Malone St Houston 77007,29.7689063,-95.419331,63,43,79
21,155,1123 Thornton Rd Houston 77018,29.832356,-95.423062,50,42,25
22,171,1132 Dunbar St Houston 77009,29.802484,-95.386033,63,46,77
23,173,1135 Nadine St Houston 77009,29.8069122,-95.3810851,63,52,67
24,178,1136 Dorothy St Houston 77008,29.7878615,-95.4088648815,70,40,74
25,180,1136 Oak Tree Dr Houston 77055,29.795899,-95.525763,67,35,68
26,181,1139 Nadine St Houston 77009,29.8069122,-95.3810851,63,52,67
27,189,1143 Lawrence Houston 77008,29.813772,-95.408224,66,42,57
28,190,1145 W 18th Street Houston 77008,29.8015449,-95.4598537,47,50,59
29,191,1145 W 18th Street Houston 77008,29.8015449,-95.4598537,47,50,59
...,...,...,...,...,...,...,...
288,1803,726 W 28th St Houston 77008,29.811999,-95.4060585,,,
289,1807,728 W 28th St Houston 77008,29.811999,-95.4060585,,,
290,1811,730 West 25th Houston 77008,29.808826,-95.414769,,,
291,1825,744 Harvard St Houston 77007,29.7759758,-95.396178,,,
292,1842,7720 Hammerly Blv Houston 77055,29.8106421,-95.4897352,,,
293,1843,7806 C Janak Dr Houston 77055,29.7993889,-95.4807349,,,
294,1859,806 Kelley St Houston 77009,29.8131,-95.365431,,,
295,1868,811 Herkimer St Houston 77007,29.7924109,-95.4061909,,,
296,1869,811 Milwaukee St Houston 77009,29.809364,-95.365378,,,
297,1870,811 W 43rd St Houston 77018,29.8326677,-95.4454245,,,
298,1873,814 Cohn St Houston 77007,29.7700061,-95.4218366,,,
299,1886,8205 Montridge Dr Houston 77055,29.8082548,-95.496149,,,
300,1890,8217 Cabernet Ln Houston 77055,29.8014432,-95.4927005,,,
301,1896,826 W 31st St Houston 77018,29.8152021,-95.4203253,,,
302,1899,828 Ennis St Houston 77003,29.751029,-95.343851,,,
303,1903,832 B W 26th St Houston 77008,29.809843,-95.414797,,,
304,1909,834 W 22nd St Houston 77008,29.805726,-95.418088,,,
305,1912,836 Nicholson Street Houston 77007,29.7924186,-95.4055829,,,
306,1921,841 Fisher #B Houston 77018,29.823067,-95.426853,,,
307,1927,844 W 17th St Houston 77008,29.800744,-95.410088,,,
308,1943,871 Fisher St Houston 77018,29.823067,-95.426853,,,
309,1951,903 Lehman St Houston 77018,29.8388825,-95.436108,,,
310,1953,904 James St Houston 77009,29.778675,-95.358307,,,
311,2000,929 Kern St Houston 77009,29.803095,-95.381907,,,
312,2009,935 Adele St Houston 77009,29.806053,-95.386179,,,
313,2014,9518 Cedarpost Square Houston 77055,29.791424,-95.5244674055,,,
314,2015,9519 Cedarpost Square Houston 77055,29.791424,-95.5244674055,,,
315,2023,963 Thornton Rd Houston 77018,29.832356,-95.423062,,,
316,2024,9756 Westview Dr Houston 77055,29.7929139,-95.528561,,,
317,2026,9809 Cedardale Dr Houston 77055,29.78997,-95.541302,,,

In [58]:
dir = "C:/Users/David/Dropbox/Skills/Python/Projects/Real_Estate/walk_score_query_py/"
file.to_csv(dir+"home_addresses_latlon_walkscores_09222017.csv")